#!/bin/bash
# *********************************************************************************** #
#                                                                                     #
#  Copyright (c) 2020 by Bodo Bauer <bb@bb-zone.com>                                  #
#                                                                                     #
#  This program is free software: you can redistribute it and/or modify               #
#  it under the terms of the GNU General Public License as published by               #
#  the Free Software Foundation, either version 3 of the License, or                  #
#  (at your option) any later version.                                                #
#                                                                                     #
#  This program is distributed in the hope that it will be useful,                    #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of                     #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                      #
#  GNU General Public License for more details.                                       #
#                                                                                     #
#  You should have received a copy of the GNU General Public License                  #
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.              #
# *********************************************************************************** #

source=/home/pi/valveControl/bin/valveControl
target=/usr/sbin/valvecontrol

if [ "$target" -ot "$source" ]; then
  /usr/sbin/service valvecontrol stop
  /usr/bin/logger "[UPDATE] Update Service valvecontrol"
  cp $source $target
  /usr/sbin/service valvecontrol start
fi
