#!/bin/sh
# *********************************************************************************** #
#                                                                                     #
#  Copyright (c) 2020 by Bodo Bauer <bb@bb-zone.com>                                 #
#                                                                                     #
#  This program is free software: you can redistribute it and/or modify               #
#  it under the terms of the GNU General Public License as published by               #
#  the Free Software Foundation, either version 3 of the License, or                  #
#  (at your option) any later version.                                                #
#                                                                                     #
#  This program is distributed in the hope that it will be useful,                    #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of                     #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                      #
#  GNU General Public License for more details.                                       #
#                                                                                     #
#  You should have received a copy of the GNU General Public License                  #
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.              #
# *********************************************************************************** #

# Start/stop the valveControl daemon
#
### BEGIN INIT INFO
# Provides:          valveControl
# Required-Start:    $network $syslog
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Automated irrigation control
# Description:       Automated irrigation control
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="Automated irrigation control"
NAME=valvecontrol
DAEMON=/usr/sbin/valvecontrol
PIDFILE=/var/run/valvecontrol.pid
CONFIGFILE=/etc/valvecontrol.cfg
SCRIPTNAME=/etc/init.d/"$NAME"
EXTRA_OPTS="-s $CONFIGFILE"

test -f $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
start)  log_daemon_msg "Starting irrigation control" "valveControl"
        start_daemon -p $PIDFILE $DAEMON $EXTRA_OPTS
        log_end_msg $?
        ;;

stop)   log_daemon_msg "Stopping irrigation control" "valveControl"
        killproc -p $PIDFILE $DAEMON
        RETVAL=$?
        [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
        log_end_msg $RETVAL
        ;;

restart) log_daemon_msg "Restarting irrigation control" "valveControl"
         $0 stop
         $0 start
         ;;

status)  status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
         ;;

*)      log_action_msg "Usage: /etc/init.d/cron {start|stop|status|restart}"
        exit 2
        ;;
esac
exit 0

