#!/bin/bash
# *********************************************************************************** #
#                                                                                     #
#  Copyright (c) 2020 by Bodo Bauer <bb@bb-zone.com>                                  #
#                                                                                     #
#  This program is free software: you can redistribute it and/or modify               #
#  it under the terms of the GNU General Public License as published by               #
#  the Free Software Foundation, either version 3 of the License, or                  #
#  (at your option) any later version.                                                #
#                                                                                     #
#  This program is distributed in the hope that it will be useful,                    #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of                     #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                      #
#  GNU General Public License for more details.                                       #
#                                                                                     #
#  You should have received a copy of the GNU General Public License                  #
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.              #
# *********************************************************************************** #

SERVICE=valvecontrol
DAEMON=/usr/sbin/valvecontrol

/bin/ps -ax | /bin/grep $DAEMON | /bin/grep -v grep > /dev/null

if [ $? -eq 1 ] ; then
  # restart service
  /usr/bin/mosquitto_pub -t "/YardControl/Watchdog" -m "Restart service $SERVICE by watchdog"
  /usr/bin/logger "[WATCHDOG] Restart service $SERVICE by watchdog"
  /usr/sbin/service $SERVICE stop
  /usr/sbin/service $SERVICE start
fi
